wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1633350493
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      - 16
      4: 3.8.8
      5: 0.12.3
      8:
      - 5
arch:
  desc: null
  value: densenet121
