name: Run benchmark

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: setup up node
        uses: actions/setup-node@v1

      - name: install dependencies
        run: pip3 install -r requirements.txt

      - name: run benchmark
        run: python3 benchmark_pruning.py

      - name: commit and push if README changed
        run: |-
          git pull
          git diff
          git config --global user.email "readme-bot@example.com"
          git config --global user.name "README-bot"
          git diff --quiet || (git add . && git commit -m "run benchmark")
          git push