name: Build README

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup up node
        uses: actions/setup-node@v1

      - name: install dependencies
        run: pip3 install -r requirements.txt

      - name: update README
        run: python3 build_steps_table.py

      - name: commit and push if README changed
        run: |-
          git pull
          git diff
          git config --global user.email "readme-bot@example.com"
          git config --global user.name "README-bot"
          git diff --quiet || (git add README.md && git commit -m "Updated README")
          git push