name: tests

on:
  push

jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup up node
        uses: actions/setup-node@v1

      - name: install dependencies
        run: pip3 install -r requirements.txt

      - name: run tests
        run: python3 tests.py
  
  run-benchmark:
    runs-on: self-hosted
    steps:
      steps:
        - name: checkout code
          uses: actions/checkout@v2

        - name: setup up node
          uses: actions/setup-node@v1

        - name: install dependencies
          run: pip3 install -r requirements.txt

        - name: run benchmark
          run: python3 benchmark_pruning.py
